const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
const React = require('react');
const {create, act} = require('react-test-renderer');
global.IS_REACT_ACT_ENVIRONMENT = true;
function load(file, mocks) {
  const output=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
  const exports={};
  vm.runInNewContext(output,{exports,require:id=>id in mocks?mocks[id]:require(id),crypto:require('node:crypto').webcrypto,window:{location:{origin:'http://localhost',replace(){}}},console,Date,Promise,setTimeout});
  return exports;
}
const q=id=>({id,qnum:Number(id.slice(1)),year:'2025a',category:'気道管理',stem:'問題 '+id,choices:{a:'選択肢A',b:'選択肢B'},answer:'a',explanation:'解説'});
async function setup() {
 const calls=[],questions={q1:q('q1'),q2:q('q2')};let fail=false;
 const helpers={getUserProfile:async()=>({username:'test',role:'user'}),getYears:async()=>['2025a'],getCategories:async()=>[],getReviewQueue:async()=>({total:2,cards:[{questionId:'q1'},{questionId:'q2'}]}),getNextQuestion:async()=>{calls.push('random');return {question:q('q9')}} ,saveAttempt:async(...args)=>{calls.push(args);if(fail)throw Error('offline');}};
 const Quiz=load('src/app/quiz/page.tsx',{'firebase/auth':{onAuthStateChanged:(_,cb)=>{cb({uid:'test'});return ()=>{};}},'@/lib/firebase':{auth:{},db:{}},'@/lib/firebaseHelpers':helpers,'@/lib/srs':{SRS_OPTIONS:[{key:'good',label:'良い',sub:'3日後'}]},'firebase/firestore':{doc:(_,c,id)=>id,getDoc:async id=>({id,exists:()=>true,data:()=>questions[id]})}}).default;
 let renderer;await act(async()=>{renderer=create(React.createElement(Quiz));});
 const text=n=>typeof n==='string'?n:(n?.children||[]).map(text).join('');
 async function click(label){const button=renderer.root.findAllByType('button').find(b=>text(b).includes(label));assert.ok(button,label);await act(async()=>{await button.props.onClick();});}
 return {calls,renderer,click,fail:v=>fail=v,text:()=>text(renderer.toJSON()),close:async()=>act(()=>renderer.unmount())};
}
test('review follows queue and finishes without random questions',async()=>{const s=await setup();await s.click('復習モード');await s.click('復習を開始');assert.match(s.text(),/問題 q1/);await s.click('選択肢A');await s.click('良い');assert.match(s.text(),/問題 q2/);await s.click('選択肢A');await s.click('良い');assert.match(s.text(),/お疲れさまでした/);assert.equal(s.calls.includes('random'),false);assert.deepEqual(s.calls.map(c=>c[1]),['q1','q2']);await s.close();});
test('finish waits for rating and saves last answer before summary',async()=>{const s=await setup();await s.click('クイズ');await s.click('選択肢A');await s.click('今日はここまで');assert.match(s.text(),/この回答を保存して終了/);await s.click('良い');assert.equal(s.calls.filter(Array.isArray).length,1);assert.match(s.text(),/お疲れさまでした/);await s.close();});
test('failed saving stays on same review question and retries with same attempt ID',async()=>{const s=await setup();await s.click('復習モード');await s.click('復習を開始');await s.click('選択肢A');s.fail(true);await s.click('良い');assert.match(s.text(),/失敗しました/);assert.match(s.text(),/問題 q1/);s.fail(false);await s.click('良い');const saves=s.calls.filter(Array.isArray);assert.equal(saves[0][5],saves[1][5]);assert.match(s.text(),/問題 q2/);await s.close();});
test('attempt retry only updates SRS once and failed transaction saves nothing',async()=>{const store=new Map();let fail=false;const timestamp=d=>({toDate:()=>d});const api={doc:(...args)=>args.filter(x=>typeof x==='string').join('/'),collection:(...args)=>args.filter(x=>typeof x==='string').join('/'),Timestamp:{fromDate:timestamp},runTransaction:async(_,fn)=>{const staged=[];const res=await fn({get:async path=>({exists:()=>store.has(path),data:()=>store.get(path)}),set:(path,data)=>staged.push([path,data])});if(fail)throw Error('offline');for(const [p,d]of staged)store.set(p,d);return res;}};let schedules=0;const {saveAttempt}=load('src/lib/firebaseHelpers.ts',{'firebase/firestore':api,'firebase/auth':{},'firebase/functions':{},'./firebase':{db:{}},'./srs':{scheduleCard:()=>{schedules++;return{nextCard:{},nextDue:new Date()};}}});fail=true;await assert.rejects(saveAttempt('u','q1','a','a','good','a1'));assert.equal(store.size,0);fail=false;await saveAttempt('u','q1','a','a','good','a1');const before=schedules;await saveAttempt('u','q1','a','a','good','a1');assert.equal(schedules,before);assert.equal(store.size,2);});
test('Functions reject forged admins and preserve muro as sole administrator',async()=>{let created=0;const admin={initializeApp(){},firestore:()=>({collection:()=>({doc:()=>({get:async()=>({exists:true,data:()=>({role:'admin'})}),set:async()=>{}})})}),auth:()=>({createUser:async()=>{created++;return{uid:'new'};},updateUser:async()=>{}})};class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}const functions=load('functions/index.js',{'firebase-admin':admin,'firebase-functions/v2/https':{onCall:fn=>fn,HttpsError}});await assert.rejects(functions.adminCreateUser({auth:{uid:'member'},data:{username:'someone',password:'test123',role:'user'}}),e=>e.code==='permission-denied');await assert.rejects(functions.changeUserPassword({auth:{uid:'member'},data:{targetUid:'other',newPassword:'test123'}}),e=>e.code==='permission-denied');await assert.rejects(functions.adminCreateUser({auth:{uid:'kuredXmbTWhCfx4dVtvdUyiZsUq1'},data:{username:'someone',password:'test123',role:'admin'}}),e=>e.code==='invalid-argument');assert.equal(created,0);assert.equal((await functions.adminCreateUser({auth:{uid:'kuredXmbTWhCfx4dVtvdUyiZsUq1'},data:{username:'someone',password:'test123',role:'user'}})).success,true);});
test('home after answering also requests saving rather than dropping answer',async()=>{const s=await setup();await s.click('クイズ');await s.click('選択肢A');await s.click('← ホーム');assert.match(s.text(),/この回答を保存して終了/);await s.click('良い');assert.equal(s.calls.filter(Array.isArray).length,1);assert.match(s.text(),/お疲れさまでした/);await s.close();});
